#!/usr/bin/env python3
"""One static page per drink, so a link to a drink is a link to a page.

A hash never leaves the phone. Every crawler that unfurls a link, from
iMessage to Facebook to Googlebot, fetches the address before the `#`
and reads the meta tags it finds there, with no JavaScript run. So the
address the Share tab hands out is `fewbottles.com/drink/<id>/`, and
this script writes that page: the name in the title, the recipe on the
page, the card image in the og tags, a Recipe block of JSON-LD naming
who pours it, and a link into the app. The page is readable with
nothing running, which is the whole point of it.

`python3 scripts/pages.py` writes drink/<id>/index.html for every drink
on the menu and sitemap.xml over the lot. `--check` refuses a stale,
missing or orphaned page the way kin.py refuses a stale kin.json.

It writes the hubs as well. A drink page is a leaf, and until one of
these existed the front page linked no leaf at all: every row on the
menu is written by app.js, so the address a crawler reads has 185
pages under it and no link to any of them. /drink/ is the index of
every drink, /menu/<family>/ is one section of my printed card, and
/shape/<pattern>/ is one of the shapes kin.py files. Both filings are
already in the data; neither is worked out here, and a third one is
not invented.

Dates. The Recipe block carries when a drink was published and last
changed, and the sitemap carries the second as lastmod. Asking git at
render time would make `--check` depend on a full clone and on commit
dates nobody can know before the commit, so data/dates.json holds both
beside a hash of the drink object. A write compares the hash: a new
drink is published today, a changed one is modified today, and the rest
keep their dates. `--check` refuses an entry whose hash no longer
matches, so an edit cannot ship with last month's date on it. The file
was seeded once from the history of data/cocktails.json.
"""
import datetime
import hashlib
import json
import sys
from html import escape
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import llms  # noqa: E402  (path set above; there is no package here)

ROOT = Path(__file__).resolve().parent.parent
PAGES = ROOT / "drink"
SITEMAP = ROOT / "sitemap.xml"
DATES = ROOT / "data" / "dates.json"
ORIGIN = "https://fewbottles.com"
AUTHOR = "Craig Johnston"
AUTHOR_URL = "https://imti.co/"
GTM = "GTM-WTFK3CCS"
KIN_SHOWN = 6
ISSUES = "https://github.com/cjimti/drink/issues"

# A hub page is a list of drinks with an address of its own, and the two
# filings it cuts the menu along are both already data: `family` is the
# section a drink prints under on my card, and the pattern kin.py files
# it as is the shape. Nothing here works out a third one. INDEX is the
# page every drink and every hub hangs off, so a crawler that reads the
# front page and nothing else still has one link to all of them.
INDEX = "drink"
HUB_DIRS = {"index": INDEX, "family": "menu", "shape": "shape"}

# Every page this script owns, as globs, so a page left behind by a drink
# or a section that is gone is found rather than served for ever.
OWNED = (f"{INDEX}/index.html", f"{INDEX}/*/index.html",
         f"{HUB_DIRS['family']}/*/index.html",
         f"{HUB_DIRS['shape']}/*/index.html")
OWNED_DIRS = (PAGES, ROOT / HUB_DIRS["family"], ROOT / HUB_DIRS["shape"])

# Names a hub's meta description lists before it says how many more.
# The index lists none: alphabetical order picks them, so they would say
# nothing about the page, and its own sentence already does.
SAMPLE = 4

# The closing line on a hub. The index does not link itself.
HUB_ALL = ('Tick the bottles you own on the <a href="/">front page</a> and '
           'the menu cuts to what you can pour tonight. Every drink on it '
           f'is in the <a href="/{INDEX}/">index</a>.')
INDEX_ALL = ('Tick the bottles you own on the <a href="/">front page</a> and '
             'the menu cuts to what you can pour tonight.')

# What the front page's own card shows, for a hub that has no card of
# its own to unfurl. The drink pages each have one; a list does not.
OG = f"{ORIGIN}/assets/og.png"
OG_SIZE = (2400, 1260)
OG_ALT = ("few bottles: line drawings of Nick & Nora and rocks glasses, "
          "empty and with twist, pick, and wheel.")

NOTE = ("Generated by scripts/pages.py. When each drink first appeared on "
        "the menu and when its entry last changed, keyed on a hash of the "
        "drink so a change is noticed without git. Seeded from git history "
        "on 2026-09-12. Do not edit by hand.")

# totalTime, in minutes, by method. A stir is thirty seconds on ice and a
# shake is fifteen, but the clock starts at the jigger; a built drink has
# no strain. A fourth method with no entry here refuses the render.
MINUTES = {"stirred": 3, "shaken": 3, "built": 2}

# Every page foot says where a correction goes. A search lands on one
# drink, and that is the page somebody finds the wrong measure on.
REPORT = (f'A wrong measure or a bad date is an issue at '
          f'<a href="{ISSUES}" rel="noopener">github.com/cjimti/drink/issues</a>.')

# The two faces the first screen is set in, served from here. A drink
# page is where a shared link lands, so it preloads them like the app
# does. crossorigin is not optional even same-origin: a font is
# fetched in CORS mode, and a preload that does not say so is fetched
# twice.
PRELOAD = ("montserrat-500-800-latin.woff2", "lato-400-latin.woff2")

GTM_HEAD = (
    "<!-- Google Tag Manager -->\n"
    "<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\n"
    "new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\n"
    "j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\n"
    "'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\n"
    f"}})(window,document,'script','dataLayer','{GTM}');</script>\n"
    "<!-- End Google Tag Manager -->\n")

GTM_BODY = (
    "<!-- Google Tag Manager (noscript) -->\n"
    f'<noscript><iframe src="https://www.googletagmanager.com/ns.html?id={GTM}"\n'
    'height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>\n'
    "<!-- End Google Tag Manager (noscript) -->\n")

MARK = ('<svg class="topbar__mark" viewBox="0 0 40 40" aria-hidden="true">'
        '<rect width="40" height="40" rx="2"/>'
        '<path d="M13 11h14l-5.4 8.4v7.4h4.1v1.9h-11.4v-1.9h4.1v-7.4z"/></svg>')


def page_url(did):
    return f"{ORIGIN}/drink/{did}/"


def card_url(did):
    return f"{ORIGIN}/assets/cards/{did}.png"


def pours(drink, by_id):
    """`1 oz Apple brandy`, one per build entry, the amount decoded."""
    return [llms.pour_text(part, by_id) for part in drink["build"]]


def description(drink, lines, serve):
    """The meta description: what is in it, then how it is served."""
    return f"{drink['name']}: {', '.join(lines)}. {drink['method'].capitalize()}, {serve.lower()}."


def head(drink, ctx):
    """Everything a crawler reads about one drink."""
    did = drink["id"]
    return meta({
        "tab": f"{escape(drink['name'])}, few bottles",
        "title": escape(drink["name"]),
        "desc": escape(ctx["desc"]),
        "url": page_url(did),
        "type": "article",
        "image": card_url(did),
        "size": (1200, 630),
        "alt": escape(f"{drink['name']}, the recipe on a card: {ctx['alt']}."),
        "extra": f'<meta property="article:author" content="{AUTHOR_URL}">\n',
        "ld": ctx["ld"],
    })


def meta(m):
    """The head every page written here carries, drink or hub.

    One block rather than two, so a tag added for a crawler lands on all
    of them. Everything in `m` is already escaped: this only assembles.
    """
    return (
        '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        + GTM_HEAD +
        '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n'
        f"<title>{m['tab']}</title>\n"
        f'<meta name="description" content="{m["desc"]}">\n'
        f'<meta name="author" content="{AUTHOR}">\n'
        '<meta name="robots" content="index, follow">\n'
        '<meta name="color-scheme" content="dark light">\n'
        '<meta name="theme-color" content="#121211" media="(prefers-color-scheme: dark)">\n'
        '<meta name="theme-color" content="#FFFFFF" media="(prefers-color-scheme: light)">\n'
        f'<link rel="canonical" href="{m["url"]}">\n'
        f'<link rel="author" href="{AUTHOR_URL}">\n'
        '<link rel="icon" href="/assets/icon.svg" type="image/svg+xml">\n'
        '<link rel="apple-touch-icon" href="/assets/icon-180.png">\n'
        f'<meta property="og:type" content="{m["type"]}">\n'
        '<meta property="og:site_name" content="few bottles">\n'
        '<meta property="og:locale" content="en_US">\n'
        f'<meta property="og:url" content="{m["url"]}">\n'
        f'<meta property="og:title" content="{m["title"]}">\n'
        f'<meta property="og:description" content="{m["desc"]}">\n'
        f'<meta property="og:image" content="{m["image"]}">\n'
        '<meta property="og:image:type" content="image/png">\n'
        f'<meta property="og:image:width" content="{m["size"][0]}">\n'
        f'<meta property="og:image:height" content="{m["size"][1]}">\n'
        f'<meta property="og:image:alt" content="{m["alt"]}">\n'
        + m["extra"] +
        '<meta name="twitter:card" content="summary_large_image">\n'
        '<meta name="twitter:site" content="@cjimti">\n'
        '<meta name="twitter:creator" content="@cjimti">\n'
        f'<meta name="twitter:title" content="{m["title"]}">\n'
        f'<meta name="twitter:description" content="{m["desc"]}">\n'
        f'<meta name="twitter:image" content="{m["image"]}">\n'
        f'<meta name="twitter:image:alt" content="{m["alt"]}">\n'
        '<script type="application/ld+json">\n' + m["ld"] + "\n</script>\n"
        + "".join(f'<link rel="preload" href="/assets/fonts/{f}" '
                  'as="font" type="font/woff2" crossorigin>\n'
                  for f in PRELOAD)
        + '<link rel="stylesheet" href="/assets/app.css">\n'
        "</head>\n")


def json_ld(drink, ctx):
    """A Recipe that names its author, on the same ids index.html uses."""
    did = drink["id"]
    steps = [ctx["how"], f"Serve: {ctx['serve'].lower()}."]
    recipe = {
        "@type": "Recipe",
        "@id": page_url(did) + "#recipe",
        "name": drink["name"],
        "url": page_url(did),
        "image": card_url(did),
        "description": ctx["desc"],
        "author": {"@id": f"{ORIGIN}/#person"},
        "isPartOf": {"@id": f"{ORIGIN}/#website"},
        "datePublished": ctx["dates"]["published"],
        "dateModified": ctx["dates"]["modified"],
        "totalTime": f"PT{MINUTES[drink['method']]}M",
        "recipeCategory": "Cocktail",
        "recipeYield": "1 drink",
        "recipeIngredient": ctx["lines"],
        "recipeInstructions": [{"@type": "HowToStep", "text": s} for s in steps],
        "keywords": ", ".join(k for k in (ctx["family"], drink["method"], ctx["shape"]) if k),
    }
    crumbs = breadcrumbs([
        ("few bottles", f"{ORIGIN}/"),
        ("Every drink", f"{ORIGIN}/{INDEX}/"),
        (ctx["family"], hub_url("family", drink["family"])),
        (drink["name"], page_url(did)),
    ])
    graph = {"@context": "https://schema.org",
             "@graph": [recipe, person(), website(), crumbs]}
    return json.dumps(graph, indent=2, ensure_ascii=False)


def person():
    """Who pours it. One node, on the id index.html already uses."""
    return {
        "@type": "Person",
        "@id": f"{ORIGIN}/#person",
        "name": AUTHOR,
        "url": AUTHOR_URL,
        "sameAs": [AUTHOR_URL, "https://x.com/cjimti", "https://github.com/cjimti"],
    }


def website():
    return {
        "@type": "WebSite",
        "@id": f"{ORIGIN}/#website",
        "url": f"{ORIGIN}/",
        "name": "few bottles",
        "publisher": {"@id": f"{ORIGIN}/#person"},
    }


def breadcrumbs(steps):
    """The trail a search result prints instead of a bare address.

    (name, address) from the front page down, so a drink reached from a
    search says which section of the menu it is on and what indexes it.
    """
    return {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i, "name": name, "item": url}
            for i, (name, url) in enumerate(steps, 1)],
    }


def topbar():
    return (
        '<header class="topbar">\n'
        f'  <a class="topbar__brand" href="/">{MARK}'
        '<span class="topbar__name">fewbottles.com</span></a>\n'
        '  <nav class="topbar__tabs" aria-label="Sections">\n'
        '    <a class="toptab" href="/#menu">Menu</a>\n'
        '    <a class="toptab" href="/#bar">Bar</a>\n'
        '    <a class="toptab" href="/#key">Key</a>\n'
        '    <a class="toptab" href="/#info">Info</a>\n'
        "  </nav>\n</header>\n")


def kin_list(drink, ctx):
    """The nearest drinks of the same shape, each a link to its own page."""
    rows = ctx["kin"].get(drink["id"], {}).get("kin", [])[:KIN_SHOWN]
    rows = [r for r in rows if r["id"] in ctx["names"]]
    if not rows:
        return ""
    items = "".join(
        f'    <li><a href="/drink/{r["id"]}/">{escape(ctx["names"][r["id"]])}</a>'
        f'<span class="page__why">{escape(r["why"])}</span></li>\n' for r in rows)
    shape = escape(ctx["shape"] or "shape")
    if ctx["pattern"]:
        shape = f'<a href="{hub_href("shape", ctx["pattern"])}">{shape}</a>'
    return (f'  <section class="page__section">\n    <h2>Same shape, other bottles</h2>\n'
            f'    <p class="page__note">The {shape} family, with the bottle that changed.</p>\n'
            f'    <ul class="page__kin">\n{items}    </ul>\n  </section>\n')


def article(drink, ctx):
    """The drink, spelled out: what goes in, how it is made, what it is."""
    did = drink["id"]
    lines = "".join(f"      <li>{escape(p)}</li>\n" for p in ctx["lines"])
    html = (
        f'  <p class="page__eyebrow"><a href="{hub_href("family", drink["family"])}">'
        f'{escape(ctx["family"])}</a>, {escape(drink["method"])}</p>\n'
        f'  <h1 class="page__name">{escape(drink["name"])}</h1>\n'
        # ARIA has no aria-label on a paragraph, so a reader dropped the
        # word and read a bare 2,1,1,cl. The word goes in the paragraph
        # instead, where nothing can ignore it.
        f'  <p class="page__code"><span class="sr-only">Barline </span>'
        f'{escape(drink["code"])}</p>\n'
        '  <p class="page__key">The code is the shorthand off my printed menu; '
        'the <a href="/#key">Key tab</a> decodes every letter.</p>\n'
        f'  <ul class="page__pours">\n{lines}    </ul>\n'
        f'  <p class="page__method">{escape(ctx["how"])}</p>\n'
        f'  <p class="page__serve">{escape(ctx["serve"])}.</p>\n'
        f'  <p class="page__open"><a class="btn" href="/#drink/{did}">Open in the menu</a></p>\n')
    if drink.get("taste"):
        html += (f'  <section class="page__section">\n    <h2>Taste</h2>\n'
                 f'    <p>{escape(drink["taste"])}</p>\n  </section>\n')
    if drink.get("history"):
        refs = "".join(
            f'      <li><a href="{escape(r["url"])}" rel="noopener">{escape(r["title"])}</a></li>\n'
            for r in drink.get("refs") or [] if r.get("title") and r.get("url"))
        html += (f'  <section class="page__section">\n    <h2>History</h2>\n'
                 f'    <p>{escape(drink["history"])}</p>\n'
                 + (f'    <ul class="recipe-refs">\n{refs}    </ul>\n' if refs else "")
                 + "  </section>\n")
    html += kin_list(drink, ctx)
    return html


def page(drink, ctx):
    n = ctx["count"]
    return (
        head(drink, ctx) + '<body class="page">\n' + GTM_BODY + topbar() +
        '<main id="main" class="page__main">\n<article class="page__drink">\n'
        + article(drink, ctx) +
        '  <p class="page__all">This is one drink on my home bar\'s menu. Tick the bottles '
        f'you own and the menu lists which of <a href="/">all {n} drinks</a> they pour, '
        f'or read the <a href="/{INDEX}/">index of every drink</a>.</p>\n'
        "</article>\n</main>\n" + foot())


def foot():
    """Who poured it and where a correction goes, on every page here."""
    return ('<footer class="page__foot">\n'
            f'  <p>My shelf, my menu. <a href="{AUTHOR_URL}" rel="author">{AUTHOR}</a>, '
            f'<a href="/">fewbottles.com</a>. {REPORT}</p>\n'
            "</footer>\n</body>\n</html>\n")


# --------------------------------------------------------------------- #
# The hubs: /drink/ over every page, and one page per filing the menu
# already carries. A drink page is a leaf, and a leaf nothing links to
# is found by the sitemap alone.
# --------------------------------------------------------------------- #


def hub_path(kind, hid):
    """`menu/gin/` or `drink/`: the folder a hub is served from."""
    return HUB_DIRS[kind] + "/" + (f"{hid}/" if hid else "")


def hub_href(kind, hid):
    return "/" + hub_path(kind, hid)


def hub_url(kind, hid):
    return ORIGIN + hub_href(kind, hid)


def hub_key(hub):
    """What makes a hub itself. `vermouth` is a section and a shape."""
    return hub["kind"], hub["id"]


def hubs(menu, kin):
    """Every hub page, in the order the sitemap lists them.

    The index, then my card's sections in card order, then the shapes
    kin.py files. A section or a shape with nothing under it is not a
    page.
    """
    names = {d["id"]: d["name"] for d in menu["cocktails"]}
    order = [d["id"] for d in menu["cocktails"]]
    family = {d["id"]: d["family"] for d in menu["cocktails"]}
    out = [index_hub(sorted(order, key=lambda i: names[i].casefold()))]
    for f in menu["families"]:
        ids = [i for i in order if family[i] == f["id"]]
        if ids:
            out.append(family_hub(f, ids))
    for pattern in kin.get("patterns", []):
        ids = [i for i in pattern["members"] if i in names]
        if ids:
            out.append(shape_hub(pattern, ids, names))
    return out


def index_hub(ids):
    """/drink/, the one page that links every other page here."""
    n = len(ids)
    return {
        "kind": "index", "id": "", "label": "Every drink", "ids": ids,
        "sample": 0,
        "tab": f"All {n} drinks, few bottles",
        "eyebrow": "Index",
        "heading": "A to Z",
        "blurb": f"Every drink on my home bar's menu, {n} of them, A to Z, "
                 f"with what goes in each.",
        "lead": "Every drink on my menu, A to Z. Each one has a page of its "
                "own with the pour, the method and the glass.",
        "all": INDEX_ALL,
    }


def family_hub(family, ids):
    """One section of the printed card, and what prints under it."""
    label, n = family["label"], len(ids)
    return {
        "kind": "family", "id": family["id"], "label": label, "ids": ids,
        "sample": SAMPLE,
        "tab": f"{label}, few bottles",
        "eyebrow": "Menu section",
        "heading": "The drinks",
        "blurb": f"The {label} section of my home bar's menu: "
                 f"{llms.plural(n, 'drink', 'drinks')}, with what goes in "
                 f"each.",
        "lead": f"{llms.plural(n, 'drink', 'drinks')} "
                f"{'prints' if n == 1 else 'print'} under {escape(label)} on "
                f"my menu. The heading is my card's own filing, and the "
                f'<a href="/">front page</a> filters on what a drink '
                f"actually contains.",
        "all": HUB_ALL,
    }


def shape_hub(pattern, ids, names):
    """One shape kin.py files, and the drinks built to it."""
    label, n = pattern["label"], len(ids)
    first = names.get(pattern.get("namesake") or "")
    near = f" Nearest the {escape(first)} first." if first else ""
    shares = "shares" if n == 1 else "share"
    return {
        "kind": "shape", "id": pattern["id"], "label": label, "ids": ids,
        "sample": SAMPLE,
        "tab": f"The {label} shape, few bottles",
        "eyebrow": "Shape",
        "heading": "The drinks",
        "blurb": f"{pattern['blurb']} "
                 f"{llms.plural(n, 'drink', 'drinks')} on my menu "
                 f"{shares} it.",
        "lead": f"{escape(pattern['blurb'])} "
                f"{llms.plural(n, 'drink', 'drinks')} on my menu "
                f"{shares} it.{near}",
        "all": HUB_ALL,
    }


def hub_desc(hub, names):
    """The meta description: what the page holds, then some of the names."""
    said = [names[i] for i in hub["ids"][:hub["sample"]]]
    if not said:
        return hub["blurb"]
    rest = len(hub["ids"]) - len(said)
    tail = ", ".join(said) + (f", and {rest} more." if rest else ".")
    return f"{hub['blurb']} {tail}"


def hub_context(menu, by_id, kin):
    """Everything every hub page needs, worked out once for all of them."""
    names = {d["id"]: d["name"] for d in menu["cocktails"]}
    lines = {d["id"]: llms.ingredient_line(d, by_id) for d in menu["cocktails"]}
    rows = hubs(menu, kin)
    refuse_unsafe_hubs(rows)
    for hub in rows:
        hub["desc"] = hub_desc(hub, names)
    return {"names": names, "lines": lines, "hubs": rows}


def refuse_unsafe_hubs(rows):
    """Stop before a section or a shape id is used as a folder name."""
    bad = [f"{h['kind']} {h['id']}" for h in rows
           if h["id"] and not llms.SAFE_ID.fullmatch(h["id"])]
    if bad:
        raise SystemExit(f"  PAGES   {', '.join(bad)} is not a slug, so no "
                         f"hub page is written for it")


def hub_ld(hub, ctx):
    """A CollectionPage over the ItemList of what it indexes."""
    url = hub_url(*hub_key(hub))
    items = [{"@type": "ListItem", "position": i, "name": ctx["names"][did],
              "url": page_url(did)} for i, did in enumerate(hub["ids"], 1)]
    collection = {
        "@type": "CollectionPage",
        "@id": url + "#page",
        "url": url,
        "name": hub["tab"],
        "description": hub["desc"],
        "isPartOf": {"@id": f"{ORIGIN}/#website"},
        "author": {"@id": f"{ORIGIN}/#person"},
        "mainEntity": {"@id": url + "#list"},
    }
    listing = {
        "@type": "ItemList",
        "@id": url + "#list",
        "name": hub["label"],
        "numberOfItems": len(items),
        "itemListElement": items,
    }
    steps = [("few bottles", f"{ORIGIN}/")]
    if hub["kind"] != "index":
        steps.append(("Every drink", f"{ORIGIN}/{INDEX}/"))
    steps.append((hub["label"], url))
    graph = [collection, listing, person(), website(), breadcrumbs(steps)]
    return json.dumps({"@context": "https://schema.org", "@graph": graph},
                      indent=2, ensure_ascii=False)


def hub_head(hub, ctx):
    """The same tags a drink page carries, over a list rather than a pour."""
    return meta({
        "tab": escape(hub["tab"]),
        "title": escape(hub["tab"]),
        "desc": escape(hub["desc"]),
        "url": hub_url(*hub_key(hub)),
        "type": "website",
        "image": OG,
        "size": OG_SIZE,
        "alt": escape(OG_ALT),
        "extra": "",
        "ld": hub_ld(hub, ctx),
    })


def hub_rows(ids, ctx):
    """One line per drink: the name, linked, and what goes in it."""
    return "".join(
        f'      <li><a href="/{INDEX}/{did}/">{escape(ctx["names"][did])}</a>'
        f'<span class="page__why">{escape(ctx["lines"][did])}</span></li>\n'
        for did in ids)


def hub_links(rows, current):
    """Every other hub, each saying how many drinks it counts.

    A count that does not lead to the list it counts is trivia, so the
    count rides the link rather than sitting beside one.
    """
    out = ""
    for kind, heading in (("family", "By menu section"), ("shape", "By shape")):
        items = "".join(
            f'      <li><a href="{hub_href(*hub_key(h))}">'
            f'{escape(h["label"])}</a><span class="page__why">'
            f'{llms.plural(len(h["ids"]), "drink", "drinks")}</span></li>\n'
            for h in rows
            if h["kind"] == kind and hub_key(h) != hub_key(current))
        out += (f'  <section class="page__section">\n    <h2>{heading}</h2>\n'
                f'    <ul class="page__kin">\n{items}    </ul>\n  </section>\n')
    return out


def hub_page(hub, ctx):
    """A heading, the drinks under it, and the way across to the others."""
    listing = (f'  <section class="page__section">\n'
               f'    <h2>{escape(hub["heading"])}</h2>\n'
               f'    <ul class="page__kin">\n{hub_rows(hub["ids"], ctx)}'
               f'    </ul>\n  </section>\n')
    across = hub_links(ctx["hubs"], hub)
    # On the index the ways in come first: the A to Z under them runs
    # the length of the menu, and a nav below it is a nav nobody reaches.
    top, bottom = (across, "") if hub["kind"] == "index" else ("", across)
    return (
        hub_head(hub, ctx) + '<body class="page">\n' + GTM_BODY + topbar() +
        '<main id="main" class="page__main">\n<div class="page__hub">\n'
        f'  <p class="page__eyebrow">{escape(hub["eyebrow"])}</p>\n'
        f'  <h1 class="page__name">{escape(hub["label"])}</h1>\n'
        f'  <p class="page__lead">{hub["lead"]}</p>\n'
        + top + listing + bottom +
        f'  <p class="page__all">{hub["all"]}</p>\n'
        "</div>\n</main>\n" + foot())


def context(drink, tables):
    """Everything a page needs that is not on the drink object itself."""
    menu, by_id, notation, kin, dates = tables
    families = {f["id"]: f["label"] for f in menu["families"]}
    labels = {p["id"]: p["label"] for p in kin.get("patterns", [])}
    row = kin.get("drinks", {}).get(drink["id"], {})
    lines = pours(drink, by_id)
    said = llms.serve_line(drink, notation, llms.garnish_codes(notation)).split(", ")
    # `Rocks, iced, lemon twist`: the glass leads, the rest reads on.
    serve = ", ".join(said[:1] + [p.lower() for p in said[1:]])
    ctx = {
        "count": len(menu["cocktails"]),
        "names": {d["id"]: d["name"] for d in menu["cocktails"]},
        "kin": kin.get("drinks", {}),
        "family": families.get(drink["family"], drink["family"]),
        "how": llms.method_line(drink, llms.methods_by_id(menu)),
        # Only a pattern kin.json names is linked: a hub is written for
        # each of those and for nothing else, so the link cannot be a 404.
        "pattern": row.get("pattern") if labels.get(row.get("pattern") or "") else "",
        "shape": labels.get(row.get("pattern") or ""),
        "lines": lines,
        "serve": serve,
        "alt": f"{', '.join(lines)}, {drink['method']}, {serve.lower()}",
        "desc": description(drink, lines, serve),
        "dates": dates[drink["id"]],
    }
    ctx["ld"] = json_ld(drink, ctx)
    return ctx


def sitemap(menu, dates, rows):
    """Every page, each with the day its drink last changed.

    changefreq and priority are gone: Google ignores both, and reads
    lastmod when it is consistently true. The front page is as new as
    the newest drink on it, and a hub as new as the newest drink it
    lists.
    """
    days = [dates[d["id"]]["modified"] for d in menu["cocktails"]]
    day_of = {d["id"]: day for d, day in zip(menu["cocktails"], days)}
    urls = [(f"{ORIGIN}/", max(days))]
    urls += [(hub_url(*hub_key(h)), max(day_of[i] for i in h["ids"]))
             for h in rows]
    urls += [(page_url(d["id"]), day) for d, day in zip(menu["cocktails"], days)]
    body = "".join(f"  <url>\n    <loc>{u}</loc>\n    <lastmod>{day}</lastmod>\n  </url>\n"
                   for u, day in urls)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + body + "</urlset>\n")


def drink_hash(drink):
    """What a drink's dates are keyed on: the whole object, as data."""
    text = json.dumps(drink, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def load_dates():
    """{id: {published, modified, hash}} as stored, or nothing yet."""
    if not DATES.exists():
        return {}
    return json.loads(DATES.read_text())["drinks"]


def dated(menu, stored, today):
    """The dates every drink on the menu should carry, as of today."""
    out = {}
    for d in menu["cocktails"]:
        was, now = stored.get(d["id"]), drink_hash(d)
        if was is None:
            out[d["id"]] = {"published": today, "modified": today, "hash": now}
        elif was["hash"] != now:
            out[d["id"]] = dict(was, modified=today, hash=now)
        else:
            out[d["id"]] = was
    return out


def check_dates(menu, stored):
    """A drink with no date, a date for an edit it has not seen, an orphan."""
    errs = []
    ids = {d["id"] for d in menu["cocktails"]}
    for d in menu["cocktails"]:
        was = stored.get(d["id"])
        if was is None:
            errs.append(f"data/dates.json has no date for {d['id']}")
        elif was["hash"] != drink_hash(d):
            errs.append(f"data/dates.json {d['id']} changed since it was dated")
    errs += [f"data/dates.json dates {i}, which is not on the menu"
             for i in sorted(set(stored) - ids)]
    if not errs and DATES.read_text() != dates_text(stored):
        errs.append("data/dates.json is not what pages.py writes")
    return errs


def dates_text(dates):
    """data/dates.json as pages.py writes it, note first."""
    doc = {"note": NOTE, "drinks": dict(sorted(dates.items()))}
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def render(dates=None):
    """{relative path: text} for every file this script owns.

    With no dates, the stored ones: what --check compares against.
    """
    menu = llms.load("cocktails.json")
    bar = llms.load("bar.json")
    notation = llms.load("notation.json")
    kin = llms.load("kin.json")
    llms.refuse_unsafe_ids(menu)
    refuse_untimed(menu)
    if dates is None:
        dates = load_dates()
    by_id = {i["id"]: i for i in bar["ingredients"]}
    tables = (menu, by_id, notation, kin, dates)
    ctx = hub_context(menu, by_id, kin)
    out = {f"{INDEX}/{d['id']}/index.html": page(d, context(d, tables))
           for d in menu["cocktails"]}
    out.update({hub_path(*hub_key(h)) + "index.html": hub_page(h, ctx)
                for h in ctx["hubs"]})
    out["sitemap.xml"] = sitemap(menu, dates, ctx["hubs"])
    return out


def refuse_untimed(menu):
    """A method with no totalTime stops the render rather than guessing."""
    missing = sorted({d["method"] for d in menu["cocktails"]} - set(MINUTES))
    if missing:
        raise SystemExit(f"  PAGES   no totalTime for method {', '.join(missing)}: "
                         f"add it to MINUTES in scripts/pages.py")


def on_disk():
    """Every page this script owns that is on disk, so an orphan shows.

    A section dropped from the card leaves a page behind that says it is
    still on the menu, exactly as a dropped drink does.
    """
    return {str(f.relative_to(ROOT)) for g in OWNED for f in ROOT.glob(g)}


def check_texts(texts, present):
    """Stale, missing or orphaned pages, as messages. Empty means clean."""
    errs = []
    for rel, body in sorted(texts.items()):
        path = ROOT / rel
        if not path.exists():
            errs.append(f"{rel} is missing")
        elif path.read_text() != body:
            errs.append(f"{rel} is stale")
    for rel in sorted(present - set(texts)):
        errs.append(f"{rel} is a page for nothing that is on the menu")
    return errs


def remove_if_empty(folder):
    """The drink/<id>/ an orphan page leaves behind, once nothing is in it."""
    if folder.parent in OWNED_DIRS and folder.is_dir() and not any(folder.iterdir()):
        folder.rmdir()


def main(argv):
    menu = llms.load("cocktails.json")
    stored = load_dates()
    if "--check" in argv:
        errs = check_dates(menu, stored)
        if not errs:
            errs = check_texts(render(), on_disk())
        for e in errs[:8]:
            print(f"  PAGES   {e}: run make pages")
        if len(errs) > 8:
            print(f"  PAGES   and {len(errs) - 8} more")
        if errs:
            return 1
        print(f"  pages   {len(menu['cocktails'])} drink page(s) and "
              f"{len(hubs(menu, llms.load('kin.json')))} hub page(s) current "
              f"and dated, sitemap.xml lists them")
        return 0
    dates = dated(menu, stored, datetime.date.today().isoformat())
    texts = render(dates)
    for rel in on_disk() - set(texts):
        (ROOT / rel).unlink()
        remove_if_empty((ROOT / rel).parent)
        print(f"  pages   removed {rel}")
    texts["data/dates.json"] = dates_text(dates)
    for rel, body in texts.items():
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
    print(f"  pages   wrote {len(menu['cocktails'])} drink page(s), "
          f"{len(texts) - len(menu['cocktails']) - 2} hub page(s), "
          f"sitemap.xml and data/dates.json")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
